# Generated by Django 3.2.7 on 2022-01-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20220102_0734'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
